# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/exam-sort-ocr',
                'doc_host': 'https://vrodriguezf.github.io',
                'git_url': 'https://github.com/vrodriguezf/exam-sort-ocr',
                'lib_path': 'exam_sort_ocr'},
  'syms': { 'exam_sort_ocr.core': { 'exam_sort_ocr.core.chat_ocr': ('core.html#chat_ocr', 'exam_sort_ocr/core.py'),
                                    'exam_sort_ocr.core.encode_image': ('core.html#encode_image', 'exam_sort_ocr/core.py'),
                                    'exam_sort_ocr.core.extract_student_info': ('core.html#extract_student_info', 'exam_sort_ocr/core.py'),
                                    'exam_sort_ocr.core.num_tokens_from_messages': ( 'core.html#num_tokens_from_messages',
                                                                                     'exam_sort_ocr/core.py'),
                                    'exam_sort_ocr.core.rename_all_exam_files': ( 'core.html#rename_all_exam_files',
                                                                                  'exam_sort_ocr/core.py'),
                                    'exam_sort_ocr.core.rename_exam_file': ('core.html#rename_exam_file', 'exam_sort_ocr/core.py'),
                                    'exam_sort_ocr.core.split_pdf': ('core.html#split_pdf', 'exam_sort_ocr/core.py')}}}
