# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/exam-sort-ocr',
                'doc_host': 'https://vrodriguezf.github.io',
                'git_url': 'https://github.com/vrodriguezf/exam-sort-ocr',
                'lib_path': 'exam_sort_ocr'},
  'syms': {'exam_sort_ocr.core': {'exam_sort_ocr.core.foo': ('core.html#foo', 'exam_sort_ocr/core.py')}}}
