# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/exam-sort-ocr',
                'doc_host': 'https://vrodriguezf.github.io',
                'git_url': 'https://github.com/vrodriguezf/exam-sort-ocr',
                'lib_path': 'exam_sort_ocr'},
  'syms': { 'exam_sort_ocr.core': { 'exam_sort_ocr.core.encode_image': ('core.html#encode_image', 'exam_sort_ocr/core.py'),
                                    'exam_sort_ocr.core.extract_info': ('core.html#extract_info', 'exam_sort_ocr/core.py'),
                                    'exam_sort_ocr.core.num_tokens_from_messages': ( 'core.html#num_tokens_from_messages',
                                                                                     'exam_sort_ocr/core.py')}}}
